# Generated by Django 5.0.4 on 2024-06-24 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandResale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('acre', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('district', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('price_per_cent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_square_feet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('primary_number', models.CharField(max_length=20, unique=True)),
                ('secondary_number', models.CharField(max_length=20, unique=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'land_resale',
            },
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_details',
            },
        ),
        migrations.CreateModel(
            name='ResidentialRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('totalfloor', models.CharField(max_length=50)),
                ('property_age', models.CharField(max_length=50)),
                ('builtup_area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('rent', models.CharField(max_length=50)),
                ('lease', models.CharField(max_length=50)),
                ('expected_rent', models.CharField(max_length=50)),
                ('expected_deposit', models.CharField(max_length=50)),
                ('expected_lease_amount', models.CharField(max_length=50)),
                ('maintenance', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'residential_rent',
            },
        ),
    ]
