# Generated by Django 5.0.3 on 2024-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('totalfloor', models.CharField(max_length=50)),
                ('property_age', models.CharField(max_length=50)),
                ('builtup_area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('rent', models.CharField(max_length=50)),
                ('lease', models.CharField(max_length=50)),
                ('expected_rent', models.CharField(max_length=50)),
                ('expected_deposit', models.CharField(max_length=50)),
                ('expected_lease_amount', models.CharField(max_length=50)),
                ('maintenance', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Residential_Rent',
            },
        ),
    ]
