# Generated by Django 5.0.4 on 2024-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_alter_landresale_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landresale',
            name='primary_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landresale',
            name='secondary_number',
            field=models.CharField(max_length=20),
        ),
    ]
